#!/usr/bin/env bash
# clean-host-verify.sh — clean-host verification driver (issue #10 AC2).
#
# Runs the release-binary checks a maintainer executes on FRESH macOS and
# Linux hosts (never in public CI, never against private repositories):
# help/version, config validation (synthetic config generated by the binary
# itself), daemon/service install/status/uninstall PLAN rendering (plans are
# never activated here), a disposable-temp-dir daemon round trip
# (scripts/clean-host-probe.py: boot, status/epoch, backup->restore,
# synthetic schedule lifecycle, fail-closed apply refusal, event snapshot).
#
# Usage (from a checkout of the exact release commit, with the downloaded
# release binary next to it):
#   scripts/clean-host-verify.sh --bin /path/to/herdr-fleet
#
# Public-data rule: this script contains no host paths, distro/user
# identity, credentials, or private repository names; every runtime path is
# derived from arguments or mktemp. POSIX-ish bash (macOS /bin/bash 3.2
# compatible — no associative arrays, no ${var,,}).

set -u

BIN=""
REPO="$(cd "$(dirname "$0")/.." && pwd)"

usage() {
    cat <<'EOF'
usage: clean-host-verify.sh --bin /path/to/herdr-fleet [--repo /path/to/release-tree]
EOF
    exit 2
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --bin)
            BIN="${2:-}"
            shift 2
            ;;
        --repo)
            REPO="${2:-}"
            shift 2
            ;;
        *)
            usage
            ;;
    esac
done

if [ -z "$BIN" ]; then
    echo "error: --bin is required" >&2
    usage
fi
if [ ! -x "$BIN" ]; then
    echo "error: --bin '$BIN' is not an executable file" >&2
    exit 2
fi
if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 is required (stdlib only)" >&2
    exit 2
fi
SCHEDULE_DOC="$REPO/schemas/fixtures/schedule/schedule.valid.json"
if [ ! -f "$SCHEDULE_DOC" ]; then
    echo "error: schedule fixture not found at $SCHEDULE_DOC (run from a" \
         "checkout of the release tree)" >&2
    exit 2
fi

FAILURES=0
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/hf-clean-host.XXXXXX")"
trap 'rm -rf "$TMP_ROOT"' EXIT
CONFIG="$TMP_ROOT/config.toml"

step() {
    echo "==> $*"
}

# C1: help/version on the downloaded artifact (not a developer checkout
# binary; --bin is the extracted archive executable).
step "C1: help/version"
"$BIN" --help >"$TMP_ROOT/help.txt" 2>&1
if [ "$?" -ne 0 ] || ! grep -q "USAGE" "$TMP_ROOT/help.txt"; then
    echo "FAIL: --help did not print usage text" >&2
    FAILURES=$((FAILURES + 1))
else
    echo "PASS: --help"
fi
"$BIN" --version >"$TMP_ROOT/version.txt" 2>&1
VERSION_EXIT=$?
VERSION_FIRST_LINE="$(head -n 1 "$TMP_ROOT/version.txt")"
case "$VERSION_FIRST_LINE" in
    herdr-fleet\ [0-9]*)
        echo "PASS: --version prints package identity ($VERSION_FIRST_LINE)"
        ;;
    *)
        echo "FAIL: --version output unexpected: $VERSION_FIRST_LINE" >&2
        FAILURES=$((FAILURES + 1))
        ;;
esac
if [ "$VERSION_EXIT" -ne 0 ]; then
    echo "FAIL: --version exited $VERSION_EXIT" >&2
    FAILURES=$((FAILURES + 1))
fi
if ! grep -q "state schema version:" "$TMP_ROOT/version.txt"; then
    echo "FAIL: --version lacks the state schema version fact" >&2
    FAILURES=$((FAILURES + 1))
fi

# C2: config validation with a synthetic config the binary itself generates.
step "C2: config init + validate"
"$BIN" config init >"$CONFIG" 2>"$TMP_ROOT/config-init.err"
if [ "$?" -ne 0 ]; then
    echo "FAIL: config init exited non-zero" >&2
    FAILURES=$((FAILURES + 1))
else
    echo "PASS: config init"
fi
"$BIN" config validate --config "$CONFIG" >"$TMP_ROOT/validate.txt" 2>&1
if [ "$?" -ne 0 ]; then
    echo "FAIL: config validate rejected the generated config" >&2
    FAILURES=$((FAILURES + 1))
else
    echo "PASS: config validate"
fi

# C3: daemon/service install/status/uninstall PLANS render (nothing is ever
# activated on the host service manager by this script).
step "C3: service plan rendering (no activation)"
for PLAN in install-plan status-plan uninstall-plan; do
    "$BIN" service "$PLAN" --config "$CONFIG" >"$TMP_ROOT/$PLAN.txt" 2>&1
    RC=$?
    if [ "$RC" -ne 0 ] || [ ! -s "$TMP_ROOT/$PLAN.txt" ]; then
        echo "FAIL: service $PLAN exited $RC or printed nothing" >&2
        FAILURES=$((FAILURES + 1))
    else
        echo "PASS: service $PLAN"
    fi
done

# C4: daemon round trip in disposable temp dirs (backup/restore, synthetic
# schedule workflow, fail-closed apply refusal, event snapshot).
step "C4: daemon round trip (clean-host-probe.py)"
"$BIN" --version >/dev/null 2>&1
python3 "$REPO/scripts/clean-host-probe.py" \
    --bin "$BIN" \
    --schedule-doc "$SCHEDULE_DOC" \
    >"$TMP_ROOT/probe.txt" 2>&1
PROBE_RC=$?
if [ "$PROBE_RC" -ne 0 ]; then
    echo "FAIL: clean-host probe exited $PROBE_RC" >&2
    cat "$TMP_ROOT/probe.txt" >&2
    FAILURES=$((FAILURES + 1))
else
    grep -E '^PASS:' "$TMP_ROOT/probe.txt" | sed 's/^/    /'
    echo "PASS: daemon round trip"
fi

if [ "$FAILURES" -ne 0 ]; then
    echo "clean-host verify: $FAILURES check(s) FAILED" >&2
    exit 1
fi
echo "clean-host verify: all checks passed"
